	
	* Purpose: 	Picking the last 5 words from a text
	*			This can be easily modified to pick words from anywhere in the sentence
	* Author: 	Fahad Mirza
	
	
	* Loading sample data
	* Example generated by -dataex-. For more info, type help dataex in Stata
	clear
	input str66 sentence
	"The cat is black."                                                 
	"She ran to catch the bus."                                         
	"I love eating ice cream on hot summer days."                       
	"The quick brown fox jumps over the lazy dog."                      
	"The sun shines brightly in the clear blue sky."                    
	"I enjoy long walks in the park with my dog."                       
	"The majestic mountains stand tall in the distance."                
	"Life is full of surprises."                                        
	"Yesterday, I went shopping and bought a new dress."                
	"The rain pitter-pattered on the rooftop."                          
	"Time flies when you're having fun."                                
	"Dreams can come true if you believe in them."                      
	"The old man sat on the porch, reminiscing about his youth."        
	"Happiness can be found in the simplest of things."                 
	"The butterfly gracefully flutters its wings in the garden."        
	"The sound of waves crashing on the shore is soothing."             
	"The bookshelf is filled with books of various genres."             
	"Success comes to those who work hard and never give up."           
	"The sun sets in a blaze of colors, painting the sky."              
	"Music has the power to touch the depths of our souls."             
	"The laughter of children is infectious and brings joy to everyone."
	"The aroma of freshly brewed coffee fills the room."                
	"Patience is a virtue that leads to great rewards."                 
	"The moonlight bathes the world in a mystical glow."                
	"Change is the only constant in life."                              
	"The first step towards success is believing in yourself."          
	end



	* First we compress our dataset
	compress
	
	* Specifying in local how many last words we want to keep from a sentence
	local last = 5
	
	* Remove excess spaces from text
	replace sentence = lower(trim(itrim(sentence)))
	
	* Generate word count for address in case we want to pick the last words
	generate word_count = wordcount(sentence)
	
	* If we want to pick words from in between then we do not require a word_count
	* but instead we specify in place of word_count, the position from where
	* we want to pick the words
	* Essentially this means replacing word_count with your own value
	
	* Picking the last X words if word length is greater than or equal to x
	generate start = word_count - `last' if word_count >= `last'
	
	* Generating an empty variable 
	capture drop words_`last'
	generate words_`last' = ""
	
	* Looping over the text to pick words and save them in a separate variable
	forvalues i = 1/`=_N' {
		
		local text "`=sentence[`i']'"
		
		if missing(`=start[`i']') {
			
			local ++i 	//This means that text length is less than the specified number of words we want to pick
			
		}
		
		else {
			forvalues j = `=start[`i'] + 1'/`=word_count[`i']' {
			
				local a : word `j' of `text'
				replace words_`last' = words_`last' + "`a' " in `i'
				
			}
		
		}
		
	}
	
	
	* Trimming the newly extracted words to remove spaces
	replace words_`last' = trim(words_`last')
	
	
	
	
	
	